@startuml
class Student{
+private int course;
+private String name;
public Student(){
class ByName implements Comparator<Student>{
        public int compare()
        printStudents()
                    public int compareTo(Student student)

}
class AppList {
    public static void main() {
    + List
    +Collections.sort
    }


@enduml